spring:
  profiles:
    active: dev

---

server:
  port: 8001

#mybatis
mybatis:
  type-aliases-package: com.zc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring
spring:
  profiles: dev
  application:
    name: springcloud-config-dept 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.98.47.51:3306/DB01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root3306

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 

#info
info:
  app.name: zhaocan-springcloud
  company.name: zhaocan233.top

---

server:
  port: 8001

#mybatis
mybatis:
  type-aliases-package: com.zc.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.98.47.51:3306/DB02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root3306

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 

#info
info:
  app.name: zhaocan-springcloud
  company.name: zhaocan233.top
